services:
  - type: web
    name: annonces-gratos-4
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py create_admin
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
